package tmux

import (
	"strings"
	"text/template"
)

// ThemeConf is the part of the config that follows the theme: colours
// and the footer. Sourcing it again applies a changed theme to a running
// server.
type ThemeConf struct {
	Colors Colors
	// Footer holds tmux's status rows, top to bottom, as tmux formats.
	// No rows turns the footer off.
	Footer []string
}

// Colors are what tmux draws borders, titles and the footer's
// background with, as tmux colour values; Tracks passes theme values
// ("#rrggbb").
type Colors struct {
	Border, BorderActive string
	Title, TitleActive   string
	FooterBg, FooterFg   string
	// Background replaces the terminal's own background in every pane.
	Background string
}

var themeTemplate = template.Must(template.New("theme.conf").Funcs(template.FuncMap{
	"quoted": strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace,
}).Parse(`# Generated by tracks from the theme. Do not edit.
set -g pane-border-format " #{?pane_active,#[fg={{.Colors.TitleActive}}]#[bold],#[fg={{.Colors.Title}}]}#{@tracks_title}#[default] "
set -g window-style "bg={{.Colors.Background}}"
set -g window-active-style "bg={{.Colors.Background}}"
set -g pane-border-style "fg={{.Colors.Border}},bg={{.Colors.Background}}"
set -g pane-active-border-style "fg={{.Colors.BorderActive}},bg={{.Colors.Background}}"
set -g status-style "bg={{.Colors.FooterBg}},fg={{.Colors.FooterFg}}"
{{- if .Footer}}
set -g status {{len .Footer}}
{{- range $i, $row := .Footer}}
set -g status-format[{{$i}}] "{{quoted $row}}"
{{- end}}
{{- else}}
set -g status off
{{- end}}
`))

// Render returns the file content.
func (c ThemeConf) Render() (string, error) {
	return render(themeTemplate, c)
}

// Write renders the file to path, creating its directory.
func (c ThemeConf) Write(path string) error {
	return write(themeTemplate, c, path)
}
