package tmux

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

// Conf describes the config Tracks generates for its tmux server.
type Conf struct {
	// Version of the installed tmux; newer features are only enabled
	// when it supports them.
	Version Version
	// DefaultTerminal is the TERM inside panes, "tmux-256color" where
	// the terminfo entry exists.
	DefaultTerminal string
	// OuterTerm is the TERM of the terminal starting the server, and
	// TrueColor whether it reported 24-bit colour ($COLORTERM). Only
	// then does tmux send 24-bit colour to it; other terminals get the
	// nearest colour they support.
	OuterTerm string
	TrueColor bool
	// OverrideFile is the user's own tmux config for this server,
	// sourced last when it exists.
	OverrideFile string
	// Command runs this Tracks from key bindings: the quoted binary
	// and its profile flags.
	Command string
	// Colors come from theme tokens.
	Colors Colors
}

// Colors are what tmux draws borders and titles with, as tmux colour
// values; Tracks passes theme values ("#rrggbb").
type Colors struct {
	Border, BorderActive string
	Title, TitleActive   string
}

var confTemplate = template.Must(template.New("tmux.conf").Funcs(template.FuncMap{
	"v": func(major, minor int) Version { return Version{major, minor} },
}).Parse(`# Generated by tracks on every start. Do not edit.
# Personal overrides: {{.OverrideFile}}
set -g default-terminal "{{.DefaultTerminal}}"
set -as terminal-features ",*:extkeys"
{{- if and .TrueColor .OuterTerm}}
set -as terminal-features ",{{.OuterTerm}}:RGB"
{{- end}}
set -g escape-time 0
set -g extended-keys on
set -g focus-events on
set -g mouse on
set -g set-clipboard on
set -g history-limit 50000
set -g renumber-windows on
set-environment -g COLORTERM truecolor
set-environment -g TRACKS_NEW_APP 1
set-environment -gu TRACKS_ID
set-environment -gu TRACKS_SOCKET_DIR

set -g pane-border-status top
set -g pane-border-format " #{?pane_active,#[fg={{.Colors.TitleActive}}]#[bold],#[fg={{.Colors.Title}}]}#{@tracks_title}#[default] "
set -g pane-border-style "fg={{.Colors.Border}}"
set -g pane-active-border-style "fg={{.Colors.BorderActive}}"
bind-key t run-shell -b "{{.Command}} trackwin add-terminal '#{window_id}'"
{{- if .Version.AtLeast (v 3 4)}}
set -as terminal-features ",*:hyperlinks"
{{- end}}
source-file -q "{{.OverrideFile}}"
`))

// Render returns the config file content.
func (c Conf) Render() (string, error) {
	var b bytes.Buffer
	if err := confTemplate.Execute(&b, c); err != nil {
		return "", fmt.Errorf("render tmux config: %w", err)
	}
	return b.String(), nil
}

// Write renders the config to path, creating its directory.
func (c Conf) Write(path string) error {
	content, err := c.Render()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}
